### ISSUE TITLE
Libros de IVA en PDF  y archivos Iva Digital en TXT

### ISSUE THREAD

**Issue by wgtoneatto** [codize-app/odoo-argentina#14]
Hola Ignacio, buen día, estoy trabajando con odoo 14 y 15, en ubuntu 20.04 lts, con localización argentina codize, lo que sucede es que al generar los libros de iva, si no hay movimientos, los genera, tanto el .pdf como .xlsx, pero al generarlos con movimientos me da el siguiente error al imprimir .pdf:
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1210>", line 948, in template_1210
  File "<template_1210>", line 936, in t_call_content
  File "<template_1210>", line 254, in t_call_content
AttributeError: 'account.move' object has no attribute 'amount_by_group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 2018, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/odoo-server/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/sources/report_xlsx/controllers/main.py", line 47, in report_routes
    return super(ReportController, self).report_routes(
  File "/opt/odoo/odoo-server/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1947, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo-server/addons/account/models/ir_actions_report.py", line 49, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 897, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 941, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 677, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1985, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/opt/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1993, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/opt/odoo/odoo-server/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
odoo.addons.base.models.qweb.QWebException: 'account.move' object has no attribute 'amount_by_group'
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1210>", line 948, in template_1210
  File "<template_1210>", line 936, in t_call_content
  File "<template_1210>", line 254, in t_call_content
AttributeError: 'account.move' object has no attribute 'amount_by_group'

Error when render the template
AttributeError: 'account.move' object has no attribute 'amount_by_group'
Template: 1210
Path: /t/t/t/t/div/table/tbody/tr[1]/td[7]/t[2]
Node: <t t-foreach="invoice.amount_by_group" t-as="tax"/>

tampoco  me genera los archivos de IVA DIGITAL en TXT
que puede estar pasando?

**Comment by ibuioli** [comment]
Buenas, es raro porque para la fecha de publicación de este issue habíamos subido ya hacía tiempo el parche con el error del amount_by_group (ese campo dejó de existir en 15). Para 16 directamente ni lo usamos.
