### ISSUE TITLE
Transferencias

### ISSUE THREAD

**Issue by wgtoneatto** [codize-app/odoo-argentina#7]
Hola Ignacio, buen día, estoy trabajando con odoo 15 en ubuntu 20.04 lts, con localización argentina codize.
Al tratar de guardar/confirmar una transferencia, me da este error:

RPC_ERROR

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo15/odoo15/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo15/odoo15/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo15/odoo15/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo15/odoo15/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo15/odoo15/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo15/odoo15/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo15/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo15/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo15/odoo15/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo15/odoo15/odoo/api.py", line 462, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo15/odoo15/odoo/api.py", line 442, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-207>", line 2, in create
  File "/opt/odoo15/odoo15/odoo/api.py", line 391, in _model_create_single
    return create(self, arg)
  File "/opt/odoo15/sources/odoo-argentina-codize/account_payment_group/models/account_payment.py", line 355, in create
    payment = super(AccountPayment, self).create(vals)
  File "<decorator-gen-187>", line 2, in create
  File "/opt/odoo15/odoo15/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo15/odoo15/addons/account/models/account_payment.py", line 693, in create
    payments = super().create(vals_list)
  File "<decorator-gen-131>", line 2, in create
  File "/opt/odoo15/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo15/addons/mail/models/mail_thread.py", line 265, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo15/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo15/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo15/odoo15/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo15/odoo/models.py", line 4070, in create
    records = self._create(data_list)
  File "/opt/odoo15/odoo15/odoo/models.py", line 4134, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/opt/odoo15/odoo15/odoo/fields.py", line 2530, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/opt/odoo15/odoo15/odoo/fields.py", line 2542, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo15/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo15/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for account.payment.payment_type: 'transfer'

Que puede estar sucediendo?

**Comment by ibuioli** [comment]
En realidad ya desde Odoo 14 que no se pueden hacer transferencias en Odoo. Si lo que necesitas es una transferencia interna te conviene esto: https://github.com/ExemaxSAS/account_internal_transfer
El error ese lo resolvimos en 14 dando de alta el type nuevamente, pero en 15 todavía no decidimos si se va a volver a abrir.

**Comment by wgtoneatto** [comment]
Gracias Ignacio
